[velero] feat: add nodeselector for restic
vmware-tanzu/helm-charts pull request #218
Opened 2021-02-17 18:57 UTC by peterekhator

Signed-off-by: Peter Ekhator <peterekhator@gmail.com>

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the values.yaml or README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

2021-02-18 01:03 UTC, jenting requested changes

2021-02-18 01:03 UTC, jenting commented on charts/velero/templates/restic-daemonset.yaml
> +      {{- end }}
Suggestion change
```yaml
      {{- with .Values.restic.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2021-02-18 01:55 UTC, peterekhator commented on charts/velero/templates/restic-daemonset.yaml
> +      {{- end }}
thanks @jenting. pushed an update

2021-02-18 01:56 UTC, jenting submitted a review, later dismissed
Thank you 🚀

2021-02-18 01:57 UTC, jenting commented
@carlisia @cpanato PTAL

2021-02-24 13:09 UTC, cpanato approved these changes

2021-02-24 16:13 UTC, jenting approved these changes

2021-02-24 18:42 UTC, merged