[velero] Allow better customization for upgrade-crds job
vmware-tanzu/helm-charts pull request #257
Opened 2021-04-22 19:53 UTC by uncycler

Signed-off-by: Frederic Marchand <fred@mautadine.com>

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the values.yaml or README.md
- [X] Title of the PR starts with chart name (e.g. `[velero]`)

2021-04-22 21:53 UTC, jenting reviewed
Thanks for your contribution.
Would you mind add change for the clean-up CRDs Job also?
https://github.com/vmware-tanzu/helm-charts/blob/92fcb94/charts/velero/templates/cleanup-crds.yaml#L26-L27

2021-04-27 08:26 UTC, jenting requested changes

2021-04-27 08:26 UTC, jenting commented on charts/velero/values.yaml
> +  # Pod annotations for the upgrade crds job
```suggestion
  # Pod annotations for the upgrade/cleanup CRDs Job
```

2021-04-27 08:26 UTC, jenting commented on charts/velero/values.yaml
> +  # Pod labels for the upgrade crds job
```suggestion
  # Pod labels for the upgrade/cleanup CRDs Job
```

2021-04-27 08:26 UTC, jenting commented on charts/velero/templates/upgrade-crds.yaml
> +      {{- end }}
```suggestion
      {{- with .Values.crdsJob.podLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crdsJob.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2021-04-27 08:26 UTC, jenting commented on charts/velero/templates/cleanup-crds.yaml
> +      {{- end }}
```suggestion
      {{- with .Values.crdsJob.podLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crdsJob.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2021-04-27 15:28 UTC, jenting commented
Could you please rebase the commits and add the sign-off-by? Thank you.

2021-04-28 02:15 UTC, jenting requested changes

2021-04-28 02:15 UTC, jenting commented on charts/velero/templates/cleanup-crds.yaml
>            imagePullPolicy: IfNotPresent
```suggestion
          imagePullPolicy: {{ .Values.crdsJob.image.pullPolicy }}
```

2021-04-29 07:03 UTC, jenting commented
All good except the DCO not pass.

2021-04-29 17:23 UTC, phin1x commented
@uncycler could you please sign off you commit as described here: https://github.com/vmware-tanzu/helm-charts/pull/257/checks?check_run_id=2466426563

2021-04-30 13:43 UTC, uncycler commented
> @uncycler could you please sign off you commit as described here: https://github.com/vmware-tanzu/helm-charts/pull/257/checks?check_run_id=2466426563
> 
> the sign off is required for merging

Yes, sorry! Since the command provided in the documentation seems to work only on the last commit, I did this instead:
git commit --amend -s -c e509f22d72b25edbf19bde43f18bbe9d831345af

Hope it's ok now

2021-04-30 13:48 UTC, jenting commented
I'd recommend you run
```
git rebase -i e509f22d72b25edbf19bde43f18bbe9d831345af
```
And change `pick` to `reword`, then add DCO to each commit message.
Finally, force push to your branch.

2021-05-01 16:57 UTC, ndegory commented
@uncycler @jenting shouldn't the kubectl image also be upgraded to a more recent version? Not sure what minimum Kubernetes version this chart should be compatible with, but 1.14 starts to feel old. Now that it's available through the values file, it would be good to have a sane default for most users (so something like 1.19, based on the current K8s releases).

2021-05-02 10:51 UTC, jenting commented
The best way is detect the kubernetes version without kubectl, but by curl to request kube-apiserver in order to get the current kubernetes version (also, does not need authentication).

After that, download corresponding kubectl CLI version, that would be great to use the same version as kube-apiserver.

2021-05-04 14:56 UTC, jenting commented
Could you please resolve the conflicts?

2021-05-05 14:38 UTC, jenting approved these changes

2021-05-06 01:37 UTC, jenting approved these changes

2021-05-06 15:01 UTC, foosinn commented
Would love to see this merged!

2021-05-07 01:26 UTC, jenting approved these changes

2021-05-07 03:29 UTC, carlisia approved these changes
👍

2021-05-07 03:29 UTC, merged