[velero] Update owners
vmware-tanzu/helm-charts pull request #272
Opened 2021-06-02 22:49 UTC by jenting

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] ~Variables are documented in the values.yaml or README.md~
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

2021-06-07 23:01 UTC, zubron requested changes

2021-06-07 23:01 UTC, zubron commented on charts/velero/Chart.yaml
> +  - name: bridget
Should this be my github username? In that case, it should be `zubron`.

2021-07-06 20:15 UTC, zubron reviewed
LGTM! I'll review again once it's been rebased. Thanks :)

2021-07-06 20:35 UTC, zubron reviewed
The change looks fine but I realised we're now at two maintainers, and you are the most significant contributor, @jenting! This will make it difficult for you to get changes merged. Can we add one of the other Velero maintainers here? @dsu-igeek @sseago

2021-07-21 12:05 UTC, zubron commented
We can add @reasonerjt and @ywk253100 into the list as well.

2021-07-21 12:45 UTC, zubron approved these changes
Thanks, @jenting!

2021-07-21 13:18 UTC, sseago approved these changes

2021-07-21 13:46 UTC, merged