[velero] docs: fix helm 3 argument order
vmware-tanzu/helm-charts pull request #309
Opened 2021-09-28 08:28 UTC by dunglas

Fix argument order.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the values.yaml or README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

2021-09-30 15:15 UTC, jenting requested changes
Good catch!
Could you please bump the chart version as well?

2021-09-30 15:26 UTC, jenting commented
I put a commit to bump Chart version.

2021-09-30 15:26 UTC, jenting approved these changes

2021-10-01 10:55 UTC, sseago approved these changes

2021-10-01 10:55 UTC, merged