Since velero-plugin-for-csi and features=EnableCSI are required to enable velero-plugin-for-aws, I added them to the comments for clarity.
vmware-tanzu/helm-charts pull request #319
Opened 2021-10-31 00:45 UTC by kahirokunn

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the values.yaml or README.md
- [ ] Title of the PR starts with chart name (e.g. `[velero]`)

2021-10-31 05:49 UTC, jenting requested changes
The chart version needs to bump.

2021-10-31 11:34 UTC, kahirokunn commented
@jenting thx. I did it.

2021-11-01 17:56 UTC, jenting approved these changes

2021-11-08 03:46 UTC, jenting commented
Probably we need to revisit the #166

2021-11-09 16:22 UTC, sseago approved these changes

2021-11-09 16:22 UTC, merged