[velero] Only install ServiceMonitor when monitoring API is available
vmware-tanzu/helm-charts pull request #370
Opened 2022-05-10 14:42 UTC by ariep

Signed-off-by: Arie Peterson <arie@greenhost.nl>

#### Special notes for your reviewer:
With this change, the ServiceMonitor is only installed if the corresponding monitoring API is available on the cluster (and the proper helm values are enabled, as before). This way, we can safely enable the servicemonitor in our helm values for velero that are used on many clusters, some of which have the monitoring API/prometheus and some of which do not. The unattractive alternative would be to have some complex mechanism to conditionally set the helm value depending on the cluster configuration.

This is inspired by the [same construct in another helm chart](https://github.com/ory/k8s/blob/master/helm/charts/hydra/templates/service-admin.yaml#L28).

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the values.yaml or README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

2022-05-10 18:17 UTC, sseago approved these changes

2022-05-12 01:11 UTC, jenting reviewed
Code LGTM, please help bump the chart version.

2022-05-12 14:49 UTC, ariep commented
> Code LGTM, please help bump the chart version.

Have to run to keep up :). Done!

2022-05-12 14:53 UTC, jenting approved these changes

2022-05-12 14:54 UTC, jenting requested changes
CI failed, could you check?

2022-05-17 09:54 UTC, ariep commented
> CI failed, could you check?

I'm not really sure what's going wrong. From one of the CI jobs:
```
==> Linting charts/velero
Error:  templates/: parse error at (velero/templates/servicemonitor.yaml:1): unclosed action
```
However, when I run `helm lint` or `helm lint --strict` locally (with helm 3.8.2), linting succeeds. I found [one issue](https://github.com/arttor/helmify/issues/11) with the same error message, which was solved by upgrading helm. Also, I notice that the CI job uses `quay.io/helmpack/chart-testing:v3.0.0`, which is almost two years old. Would you be willing to update that, so it uses a newer helm version for the chart testing internally, and retry the CI with that?

2022-05-17 11:34 UTC, jenting commented
Sure, we could update the helm version.

2022-05-19 15:56 UTC, jenting commented
I create #373 to update the helm version.

2022-05-20 03:17 UTC, jenting commented
@ariep Please rebase to the main branch.

2022-05-23 09:24 UTC, jenting commented
/rebase

2022-05-24 10:24 UTC, jenting approved these changes

2022-05-24 12:31 UTC, ywk253100 approved these changes

2022-05-24 12:31 UTC, merged

2022-05-24 12:46 UTC, jenting commented
Oops, we forget to bump the chart version, so the chart release failed.
We need to check on why CI did not catch this error.