velero Added affinity to restic
vmware-tanzu/helm-charts pull request #396
Opened 2022-08-25 14:42 UTC by pkbgb

#### Special notes for your reviewer:
Added affinity to restic daemonset to bring it inline with velero deployment

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the values.yaml or README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Peter Bone <peter.bone@glassbox.com>

2022-08-31 03:00 UTC, jenting approved these changes

2022-08-31 03:01 UTC, jenting requested changes
Could you please bump the chart version to `2.31.4`? https://github.com/vmware-tanzu/helm-charts/blob/97910bed0419e81e5478c520427dfe17e2a620c3/charts/velero/Chart.yaml#L6

2022-09-07 02:37 UTC, jenting approved these changes

2022-09-07 02:40 UTC, ywk253100 approved these changes

2022-09-07 02:40 UTC, merged