[velero] Adding scheme and tlsConfig values to serviceMonitor template
vmware-tanzu/helm-charts pull request #404
Opened 2022-09-19 20:26 UTC by rgarcia6520

Signed-off-by: garcia.ryan <garcia.ryan@solute.us>

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the values.yaml or README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

Closes #403

2022-09-21 05:42 UTC, jenting requested changes

2022-09-21 05:42 UTC, jenting commented on charts/velero/values.yaml
> +    enabled: true
Please default to false to keep the backward compatible.

2022-09-21 05:42 UTC, jenting commented on charts/velero/values.yaml
> +    scheme: "https"
Since the default is HTTP, why do we put it as HTTPS?

2022-09-21 05:42 UTC, jenting commented on charts/velero/values.yaml
> +      caFile: /etc/ssl/HAHA.pem
Please use the default value here. E.g.,
`tlsConfig: {}`

2022-09-21 14:16 UTC, rgarcia6520 commented
@jenting Apologies, accidentally had comitted test values I put in there to ensure things templated correctly, values file is updated

2022-09-22 00:09 UTC, jenting commented
> @jenting Apologies, accidentally had comitted test values I put in there to ensure things templated correctly, values file is updated

Thank for your contribution.

If you want to test against CI, you could change the value under ci folder.

2022-09-22 02:09 UTC, jenting approved these changes

2022-09-22 19:45 UTC, sseago approved these changes

2022-09-22 19:45 UTC, merged